# Generated by Django 5.1.7 on 2025-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0004_rename_status_aprovacao_registro_status_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='status_rh',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
