# Generated by Django 5.1.7 on 2025-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0005_registro_status_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='dias_para_aprovacao_diretor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
