# Generated by Django 5.1.7 on 2025-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0006_registro_dias_para_aprovacao_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data_aprovacao_diretor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='data_aprovacao_presidente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='dias_para_aprovacao_presidente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
