# Generated by Django 5.1.7 on 2025-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0007_registro_data_aprovacao_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data_aprovacao_rh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='dias_para_aprovacao_rh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
