# Generated by Django 5.1.7 on 2025-04-02 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0008_registro_data_aprovacao_rh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutroRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('gestor', models.ForeignKey(limit_choices_to={'user_type': 'gestor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
