# Generated by Django 5.1.7 on 2025-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0009_outroregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outroregistro',
            name='gestor',
        ),
        migrations.AddField(
            model_name='outroregistro',
            name='cargo_gestor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outroregistro',
            name='nome_gestor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
