# Generated by Django 5.1.7 on 2025-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0011_alter_outroregistro_cargo_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outroregistro',
            name='data_aprovacao_diretor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outroregistro',
            name='status_diretor',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
