# Generated by Django 5.1.7 on 2025-04-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0015_outroregistro_dias_para_aprovacao_diretor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='data_registro',
            new_name='data_criacao',
        ),
    ]
