# Generated by Django 5.1.7 on 2025-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0016_rename_data_registro_registro_data_criacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='RequisicaoPessoal',
        ),
    ]
