# Generated by Django 5.1.7 on 2025-04-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0017_rename_registro_requisicaopessoal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutroRegistro',
            new_name='MovimentacaoPessoal',
        ),
    ]
