# Generated by Django 5.1.7 on 2025-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0018_rename_outroregistro_movimentacaopessoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='status_diretor',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='status_presidente',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='status_rh',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='status_diretor',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='status_presidente',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='status_rh',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
    ]
