# Generated by Django 5.1.7 on 2025-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0019_alter_movimentacaopessoal_status_diretor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status_diretor', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20)),
                ('data_aprovacao_diretor', models.DateTimeField(blank=True, null=True)),
                ('dias_para_aprovacao_diretor', models.IntegerField(blank=True, null=True)),
                ('status_presidente', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20)),
                ('data_aprovacao_presidente', models.DateTimeField(blank=True, null=True)),
                ('dias_para_aprovacao_presidente', models.IntegerField(blank=True, null=True)),
                ('status_rh', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20)),
                ('data_aprovacao_rh', models.DateTimeField(blank=True, null=True)),
                ('dias_para_aprovacao_rh', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
