# Generated by Django 5.1.7 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0023_alter_requisicaopessoal_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='colaborador_desligado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='justificativa_aviso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='justificativa_desligamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='motivo_desligamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='outro_motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='requisitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='substituicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='tipo_aviso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='tipo_desligamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
