# Generated by Django 5.1.7 on 2025-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0024_remove_requisicaodesligamento_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='centro_custo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='colaborador_desligado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='data_admissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='data_desligamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='funcao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='justificativa_aviso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='justificativa_desligamento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='localidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='matricula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='motivo_desligamento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='outro_motivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='requisitante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='salario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='substituicao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='tipo_aviso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='tipo_desligamento',
            field=models.CharField(max_length=100),
        ),
    ]
