# Generated by Django 5.1.7 on 2025-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0027_alter_movimentacaopessoal_cargo_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='periodo',
            field=models.CharField(max_length=100),
        ),
    ]
