# Generated by Django 5.1.7 on 2025-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0028_alter_movimentacaopessoal_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('diretor', 'Diretor'), ('presidente', 'Presidente'), ('rh', 'RH'), ('complice', 'Complice')], max_length=20),
        ),
    ]
