# Generated by Django 5.1.7 on 2025-04-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0029_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='data_autorizacao_complice',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='data_autorizacao_gestor_proposto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_complice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_gestor_proposto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='status_complice',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='status_gestor_proposto',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado')], default='pendente', max_length=20),
        ),
    ]
