# Generated by Django 5.1.7 on 2025-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0030_movimentacaopessoal_data_autorizacao_complice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='n_rp',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
