# Generated by Django 5.1.7 on 2025-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0033_alter_requisicaopessoal_n_rp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='n_rp',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
