# Generated by Django 5.1.7 on 2025-04-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0034_alter_requisicaopessoal_n_rp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='status_complice',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='status_diretor',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='status_gestor_proposto',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='status_presidente',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='status_rh',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='status_diretor',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='status_presidente',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='status_rh',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='status_diretor',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='status_presidente',
        ),
        migrations.RemoveField(
            model_name='requisicaopessoal',
            name='status_rh',
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='assinatura_complice',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/complice/'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='assinatura_gestor_proposto',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/'),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/'),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/'),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/'),
        ),
    ]
