# Generated by Django 5.1.7 on 2025-04-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0035_remove_movimentacaopessoal_status_complice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_complice',
            field=models.ImageField(upload_to='assinaturas/complice/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_diretor',
            field=models.ImageField(upload_to='assinaturas/diretor/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_gestor_proposto',
            field=models.ImageField(upload_to='assinaturas/gestor/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_presidente',
            field=models.ImageField(upload_to='assinaturas/presidente/'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_diretor',
            field=models.ImageField(upload_to='assinaturas/diretor/'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_presidente',
            field=models.ImageField(upload_to='assinaturas/presidente/'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_rh',
            field=models.ImageField(upload_to='assinaturas/rh/'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_diretor',
            field=models.ImageField(upload_to='assinaturas/diretor/'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_presidente',
            field=models.ImageField(upload_to='assinaturas/presidente/'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_rh',
            field=models.ImageField(upload_to='assinaturas/rh/'),
        ),
    ]
