# Generated by Django 5.1.7 on 2025-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0036_alter_movimentacaopessoal_assinatura_complice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_complice',
            field=models.ImageField(upload_to='assinaturas/complice/MovimentacaoPessoal/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_diretor',
            field=models.ImageField(upload_to='assinaturas/diretor/MovimentacaoPessoal/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_gestor_proposto',
            field=models.ImageField(upload_to='assinaturas/gestor/MovimentacaoPessoal/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_presidente',
            field=models.ImageField(upload_to='assinaturas/presidente/MovimentacaoPessoal/'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/MovimentacaoPessoal/'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_diretor',
            field=models.ImageField(upload_to='assinaturas/diretor/RequisicaoDesligamento/'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_presidente',
            field=models.ImageField(upload_to='assinaturas/presidente/RequisicaoDesligamento/'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_rh',
            field=models.ImageField(upload_to='assinaturas/rh/RequisicaoDesligamento/'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_diretor',
            field=models.ImageField(upload_to='assinaturas/diretor/RequisicaoPessoal'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_presidente',
            field=models.ImageField(upload_to='assinaturas/presidente/RequisicaoPessoal'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_rh',
            field=models.ImageField(upload_to='assinaturas/rh/RequisicaoPessoal'),
        ),
    ]
