# Generated by Django 5.1.7 on 2025-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0037_alter_movimentacaopessoal_assinatura_complice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='motivo_desligamento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='tipo_desligamento',
            field=models.CharField(max_length=200),
        ),
    ]
