# Generated by Django 5.1.7 on 2025-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0038_alter_requisicaodesligamento_motivo_desligamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='bloqueio_readmissao',
            field=models.BooleanField(default=True),
        ),
    ]
