# Generated by Django 5.1.7 on 2025-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0040_alter_requisicaodesligamento_outro_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='assinatura_gestor_requisitante',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoDesligamento'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='data_autorizacao_gestor_requisitante',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
