# Generated by Django 5.1.7 on 2025-05-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0041_requisicaodesligamento_assinatura_gestor_requisitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_gestor_requisitante',
            field=models.ImageField(upload_to='assinaturas/gestor/RequisicaoDesligamento'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='data_autorizacao_gestor_requisitante',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
