# Generated by Django 5.1.7 on 2025-05-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0042_alter_requisicaodesligamento_assinatura_gestor_requisitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='bloqueio_readmissao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
