# Generated by Django 5.1.7 on 2025-05-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0043_alter_requisicaodesligamento_bloqueio_readmissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='bloqueio_readmissao',
            field=models.BooleanField(default=False),
        ),
    ]
