# Generated by Django 5.1.7 on 2025-05-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0044_alter_requisicaodesligamento_bloqueio_readmissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='assinatura_gestor_requisitante',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='data_autorizacao_gestor_requisitante',
        ),
    ]
