# Generated by Django 5.1.7 on 2025-05-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0046_requisicaodesligamento_assinatura_gestor_requisitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='assinatura_gestor_requisitante',
        ),
        migrations.RemoveField(
            model_name='requisicaodesligamento',
            name='data_autorizacao_gestor_requisitante',
        ),
    ]
