# Generated by Django 5.1.7 on 2025-05-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0047_remove_requisicaodesligamento_assinatura_gestor_requisitante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='outro_justificativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='outro_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='tipo_ajuda_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
