# Generated by Django 5.1.7 on 2025-05-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0048_alter_movimentacaopessoal_outro_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='valor_ajuda',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
