# Generated by Django 5.1.7 on 2025-05-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0049_alter_movimentacaopessoal_valor_ajuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='outro_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
