# Generated by Django 5.1.7 on 2025-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0050_alter_movimentacaopessoal_outro_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='assinatura_gestor_atual',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/MovimentacaoPessoal/'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='data_autorizacao_gestor_atual',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
