# Generated by Django 5.1.7 on 2025-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0051_movimentacaopessoal_assinatura_gestor_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='tipo_movimentacao',
            field=models.CharField(max_length=255),
        ),
    ]
