# Generated by Django 5.1.7 on 2025-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0052_alter_movimentacaopessoal_tipo_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='justificativa_outros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='outros_cnh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
