# Generated by Django 5.1.7 on 2025-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0053_alter_requisicaopessoal_justificativa_outros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopessoal',
            name='assinatura_gestor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='data_autorizacao_gestor',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
