# Generated by Django 5.1.7 on 2025-06-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0054_requisicaopessoal_assinatura_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='assinatura_gestor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoDesligamento'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='data_autorizacao_gestor',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
