# Generated by Django 5.1.7 on 2025-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0055_requisicaodesligamento_assinatura_gestor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='numero',
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='n_mov',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
