# Generated by Django 5.1.7 on 2025-06-13 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0056_remove_movimentacaopessoal_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopessoal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
