# Generated by Django 5.1.7 on 2025-06-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0058_remove_requisicaopessoal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopessoal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
