# Generated by Django 5.1.7 on 2025-06-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0059_requisicaopessoal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
