# Generated by Django 5.1.7 on 2025-06-16 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0061_movimentacaopessoal_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
