# Generated by Django 5.1.7 on 2025-06-16 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0062_alter_movimentacaopessoal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
