# Generated by Django 5.1.7 on 2025-06-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0064_alter_requisicaodesligamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_assinadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
