# Generated by Django 5.1.7 on 2025-06-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0065_alter_requisicaopessoal_assinatura_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopessoal',
            name='assinatura_gestor_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoPessoal'),
        ),
    ]
