# Generated by Django 5.1.7 on 2025-06-20 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0066_requisicaopessoal_assinatura_gestor_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicaopessoal',
            old_name='assinatura_gestor_imagem',
            new_name='imagem_assinatura_gestor',
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='imagem_assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='imagem_assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='imagem_assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/RequisicaoPessoal'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_assinadas_como_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_assinadas_como_gestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_assinadas_como_presidente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='assinatura_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_assinadas_como_rh', to=settings.AUTH_USER_MODEL),
        ),
    ]
