# Generated by Django 5.1.7 on 2025-06-20 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0067_rename_assinatura_gestor_imagem_requisicaopessoal_imagem_assinatura_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='imagem_assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/RequisicaoDesligamento'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='imagem_assinatura_gestor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoDesligamento'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='imagem_assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/RequisicaoDesligamento'),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='imagem_assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/RequisicaoDesligamento'),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_desligamento_como_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_desligamento_como_gestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_desligamento_como_presidente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicaodesligamento',
            name='assinatura_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_desligamento_como_rh', to=settings.AUTH_USER_MODEL),
        ),
    ]
