# Generated by Django 5.1.7 on 2025-06-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0068_requisicaodesligamento_imagem_assinatura_diretor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_diretor',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_gestor_proposto',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_presidente',
        ),
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_rh',
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='data_autorizacao_complice_atual',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_complice',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/complice/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_gestor_atual',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_gestor_proposto',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/RequisicaoPessoal'),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/RequisicaoPessoal'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_assinadas_como_diretor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_gestor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_assinadas_como_gestor_atual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_gestor_proposto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_assinadas_como_gestor_proposto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_assinadas_como_presidente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_assinadas_como_rh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='data_autorizacao_gestor_proposto',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
