# Generated by Django 5.1.7 on 2025-06-23 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0070_remove_movimentacaopessoal_data_autorizacao_complice_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_complice',
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='assinatura_complice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_assinadas_como_complice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='data_autorizacao_complice',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
