# Generated by Django 5.1.7 on 2025-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0071_remove_movimentacaopessoal_dias_para_autorizacao_complice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_complice',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/complice/MovimentacaoPessoal'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_diretor',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/diretor/MovimentacaoPessoal'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_gestor_atual',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/MovimentacaoPessoal'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_gestor_proposto',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/gestor/MovimentacaoPessoal'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_presidente',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/presidente/MovimentacaoPessoal'),
        ),
        migrations.AlterField(
            model_name='movimentacaopessoal',
            name='imagem_assinatura_rh',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas/rh/MovimentacaoPessoal'),
        ),
    ]
