# Generated by Django 5.1.7 on 2025-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0072_alter_movimentacaopessoal_imagem_assinatura_complice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_complice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_diretor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_gestor_proposto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_presidente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaopessoal',
            name='dias_para_autorizacao_rh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
