# Generated by Django 5.1.7 on 2025-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0073_movimentacaopessoal_dias_para_autorizacao_complice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopessoal',
            name='diretor_aprovacao',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='presidente_aprovacao',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisicaopessoal',
            name='rh_aprovacao',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
    ]
