# Generated by Django 5.1.7 on 2025-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0074_requisicaopessoal_diretor_aprovacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='diretor_aprovacao',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='presidente_aprovacao',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisicaodesligamento',
            name='rh_aprovacao',
            field=models.CharField(blank=True, default='PENDENTE', max_length=50, null=True),
        ),
    ]
