# Generated by Django 5.1.7 on 2025-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0077_curso_filial_base_setor_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopessoal',
            name='filial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
