# Generated by Django 5.1.7 on 2025-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0078_requisicaopessoal_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='filial',
            field=models.CharField(max_length=100),
        ),
    ]
