# Generated by Django 5.1.7 on 2025-07-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0079_alter_requisicaopessoal_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexaorh.base'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexaorh.setor'),
        ),
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexaorh.filial'),
        ),
    ]
