# Generated by Django 5.1.7 on 2025-07-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0080_alter_requisicaopessoal_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaopessoal',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexaorh.cargo'),
        ),
    ]
