# Generated by Django 5.1.7 on 2025-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0081_alter_requisicaopessoal_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='centro_de_custo',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
