# Generated by Django 5.1.7 on 2025-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0082_setor_centro_de_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='centro_de_custo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
