# Generated by Django 5.1.7 on 2025-07-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexaorh', '0083_alter_setor_centro_de_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='centro_de_custo',
        ),
    ]
